name: Ubuntu
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH connection
      uses: zjwangao/GitSkills@main
      with:
        timeout-minutes: 30 # 设置SSH会话超时时间（分钟）
