name: Terraform Deploy
on: push: branches: - main
jobs: terraform: runs-on: ubuntu-latest
`steps:`
  `- name: Checkout Repository`
    `uses: actions/checkout@v2`

  `- name: Set up Terraform`
    `uses: hashicorp/setup-terraform@v1`
    `with:`
      `terraform_version: 1.9.1`

  `- name: Terraform Init`
    `run: terraform init terraform/`

  `- name: Terraform Plan`
    `run: terraform plan -out=tfplan terraform/`

  `- name: Terraform Apply`
    `run: terraform apply -auto-approve tfplan terraform/`
